version: "3.4"

networks:
  centreon-net:
    external:
      name: centreon-net

services:
  epm:
    build:
      context: .
    image: oxyure/epm:latest
    container_name: epm
    hostname: epm
    networks:
      centreon-net:
          ipv4_address: "172.36.0.233"


