#!/bin/sh
# /sbin/epm

# Error codes:
# 1.  No configuration file specified
# 30. One or more binaries are missing (grep, awk, …)
# 31. Can’t create directories


EPM_SELF=$0
EPM_CONF=$1
EPM_RUN_COUNTER=0

show_help() {
    1>&2 cat <<EOHELP

Entrypoint Manager

Usage: $0 <configuration file>

EOHELP
}

# exit 1 if no configuration file is specified.
[ -f "$1" ] || { show_help; exit 1; } 

# source configuration file
. "$1"
# source library files
. "${EPM_LIB}"
. "${EPM_DB_LIB}"
. "${EPM_PS_LIB}"


trap graceful_exit 3 15
trap restart 2
trap reload 1

wake_up

# If first argument is an existing (configuration) file: run forever
[ -f "$1" ] && while true; do run; done





