#!/bin/sh
# /sbin/epm

EPM_SELF=$0
EPM_CONF=$1
EPM_RUN_COUNTER=0

show_help() {
    1>&2 cat <<EOHELP

Entrypoint Manager

Usage: $0 <configuration file>

EOHELP
}

trap graceful_exit 2 15
trap restart 1

# exit 1 if no configuration file is specified.
[ -f "$1" ] || { show_help; exit 1; } 

# source the configuration file
. "$1"
# source files
. "${EPM_LIB}"
. "${EPM_DB_LIB}"
. "${EPM_PS_LIB}"

wake_up

echo

cat "$EPM_DB"

db_store key value
db_store joe 89
db_store bob 42
db_store joe 12
db_store bob 100

echo

cat "$EPM_DB"

db_insert bob XXXX
db_update key 999
db_update bob 00000

cat "$EPM_DB"

db_clean

cat "$EPM_DB"

db_store joe 12
db_store bob 100

db_insert 888 kkkkkkkk
db_insert 555 ggggg
db_update 888 nnn
db_insert 888 nnn
db_insert tttt 987
db_insert tttt 333
db_get 888
db_get tttt
db_store bob 100
db_store tttt TGTggtT

db_clean


# run forever
while true; do run; done





