#!/bin/sh
# /lib/epm/epm-lib

timestamp()       { printf `date -Is` && echo -n ' '; }
log()             { timestamp; echo "$1"; }
graceful_exit()   { echo "EPM exiting… Bye!"; exit 0; }
restart()         { exec "$EPM_SELF" "$EPM_CONF"; }

wake_up() {
    mkdir -p "$EPM_DB_DIR"
    touch "$EPM_DB"
}

run() {
    cat "$EPM_DB"
    run_start=$(date +%s)
    log "Starting run #${EPM_RUN_COUNTER}…"
    sleep 1."$RANDOM"
    run_elapsed=$(echo "$(date +%s) $run_start - p" | dc )
    left_to_sleep=$(echo "$EPM_RUN_DELAY $run_elapsed - p" | dc)
    EPM_RUN_COUNTER=$(( $EPM_RUN_COUNTER + 1 ))
    log "Sleeping $left_to_sleep seconds…"
    sleep $left_to_sleep
}



